#!/bin/bash
##############################################################################
# collect-cf-quota.sh
# Connects to each subaccount's CF environment via CF API v3,
# collects memory / service-instance / route quota usage,
# writes a JSON report to stdout.
#
# Required env vars:
#   BTP_USERNAME, BTP_PASSWORD
#
# Input:  ./subaccounts.json  (generated by Terraform)
# Output: JSON report to stdout
##############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SUBACCOUNTS_FILE="${SCRIPT_DIR}/subaccounts.json"

# ---------- helpers ----------
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2; }
die() { log "ERROR: $1"; exit 1; }

# ---------- validate inputs ----------
[ -f "$SUBACCOUNTS_FILE" ] || die "subaccounts.json not found at $SUBACCOUNTS_FILE"
[ -n "${BTP_USERNAME:-}" ] || die "BTP_USERNAME not set"
[ -n "${BTP_PASSWORD:-}" ] || die "BTP_PASSWORD not set"

# ---------- map region to CF API endpoint ----------
get_cf_api() {
  local region="$1"
  # Standard SAP BTP CF API pattern
  echo "https://api.cf.${region}.hana.ondemand.com"
}

# ---------- CF login for a specific region ----------
cf_login_region() {
  local region="$1"
  local cf_api
  cf_api=$(get_cf_api "$region")

  log "Logging into CF API: $cf_api"
  if ! cf api "$cf_api" >/dev/null 2>&1; then
    log "  Cannot reach CF API: $cf_api — skipping region"
    return 1
  fi
  if ! cf auth "$BTP_USERNAME" "$BTP_PASSWORD" >/dev/null 2>&1; then
    log "  CF auth failed for region $region — skipping"
    return 1
  fi
  log "  CF login successful for region: $region"
  return 0
}

# ---------- collect quota for one org ----------
collect_org_quota() {
  local org_guid="$1"
  local org_name="$2"

  # Get the quota definition assigned to this org
  local quota_guid
  quota_guid=$(cf curl "/v3/organizations/${org_guid}" 2>/dev/null | jq -r '.relationships.quota.data.guid // empty' 2>/dev/null || echo "")

  if [ -z "$quota_guid" ]; then
    log "    No quota assigned to org: $org_name — skipping"
    echo "{}"
    return
  fi

  # Fetch quota details
  local quota_json
  quota_json=$(cf curl "/v3/organization_quotas/${quota_guid}" 2>/dev/null || echo '{}')

  local total_memory total_instances total_routes
  total_memory=$(echo "$quota_json" | jq -r '.apps.total_memory_in_mb // 0' 2>/dev/null || echo "0")
  total_instances=$(echo "$quota_json" | jq -r '.services.total_service_instances // 0' 2>/dev/null || echo "0")
  total_routes=$(echo "$quota_json" | jq -r '.routes.total_routes // 0' 2>/dev/null || echo "0")

  # Fetch actual usage
  local usage_json
  usage_json=$(cf curl "/v3/organizations/${org_guid}/usage_summary" 2>/dev/null || echo '{}')
  local used_memory
  used_memory=$(echo "$usage_json" | jq -r '.usage_summary.memory_in_mb // 0' 2>/dev/null || echo "0")

  # Count service instances
  local used_instances
  used_instances=$(cf curl "/v3/service_instances?organization_guids=${org_guid}&per_page=1" 2>/dev/null | jq -r '.pagination.total_results // 0' 2>/dev/null || echo "0")

  # Count routes
  local used_routes
  used_routes=$(cf curl "/v3/routes?organization_guids=${org_guid}&per_page=1" 2>/dev/null | jq -r '.pagination.total_results // 0' 2>/dev/null || echo "0")

  # Calculate remaining (-1 means unlimited)
  local remaining_memory=-1 remaining_instances=-1 remaining_routes=-1

  if [ "$total_memory" != "-1" ] && [ "$total_memory" != "null" ] && [ "$total_memory" != "0" ]; then
    remaining_memory=$((total_memory - used_memory))
  fi
  if [ "$total_instances" != "-1" ] && [ "$total_instances" != "null" ] && [ "$total_instances" != "0" ]; then
    remaining_instances=$((total_instances - used_instances))
  fi
  if [ "$total_routes" != "-1" ] && [ "$total_routes" != "null" ] && [ "$total_routes" != "0" ]; then
    remaining_routes=$((total_routes - used_routes))
  fi

  # Output valid JSON
  jq -n \
    --arg org_name "$org_name" \
    --arg org_guid "$org_guid" \
    --argjson total_memory "$total_memory" \
    --argjson used_memory "$used_memory" \
    --argjson remaining_memory "$remaining_memory" \
    --argjson total_instances "$total_instances" \
    --argjson used_instances "$used_instances" \
    --argjson remaining_instances "$remaining_instances" \
    --argjson total_routes "$total_routes" \
    --argjson used_routes "$used_routes" \
    --argjson remaining_routes "$remaining_routes" \
    '{
      org_name: $org_name,
      org_guid: $org_guid,
      memory: { total_mb: $total_memory, used_mb: $used_memory, remaining_mb: $remaining_memory },
      service_instances: { total: $total_instances, used: $used_instances, remaining: $remaining_instances },
      routes: { total: $total_routes, used: $used_routes, remaining: $remaining_routes }
    }'
}

# ---------- main ----------
REPORT_ITEMS="[]"
SUBACCOUNT_COUNT=$(jq -r 'length' "$SUBACCOUNTS_FILE")
log "Processing ${SUBACCOUNT_COUNT} subaccounts..."

# Group subaccounts by region to minimize logins
REGIONS=$(jq -r '.[].region' "$SUBACCOUNTS_FILE" | sort -u)

for region in $REGIONS; do
  log "=== Region: $region ==="

  # Login to this region's CF API
  if ! cf_login_region "$region"; then
    # Mark all subaccounts in this region as unreachable
    REGION_SA_COUNT=$(jq -r "[.[] | select(.region == \"$region\")] | length" "$SUBACCOUNTS_FILE")
    for i in $(seq 0 $((REGION_SA_COUNT - 1))); do
      SA_ID=$(jq -r "[.[] | select(.region == \"$region\")][$i].id" "$SUBACCOUNTS_FILE")
      SA_NAME=$(jq -r "[.[] | select(.region == \"$region\")][$i].name" "$SUBACCOUNTS_FILE")

      ENTRY=$(jq -n \
        --arg id "$SA_ID" \
        --arg name "$SA_NAME" \
        --arg region "$region" \
        '{subaccount_id: $id, subaccount_name: $name, region: $region, orgs: [], status: "cf_unreachable"}')
      REPORT_ITEMS=$(echo "$REPORT_ITEMS" | jq --argjson entry "$ENTRY" '. += [$entry]')
    done
    continue
  fi

  # Process each subaccount in this region
  REGION_SUBACCOUNTS=$(jq -c "[.[] | select(.region == \"$region\")]" "$SUBACCOUNTS_FILE")
  REGION_SA_COUNT=$(echo "$REGION_SUBACCOUNTS" | jq 'length')

  for i in $(seq 0 $((REGION_SA_COUNT - 1))); do
    SA_ID=$(echo "$REGION_SUBACCOUNTS" | jq -r ".[$i].id")
    SA_NAME=$(echo "$REGION_SUBACCOUNTS" | jq -r ".[$i].name")

    log "  Subaccount: $SA_NAME ($SA_ID)"

    # Get all orgs visible in this CF environment
    ORGS_JSON=$(cf curl "/v3/organizations" 2>/dev/null || echo '{"resources":[]}')
    ORG_COUNT=$(echo "$ORGS_JSON" | jq '.resources | length' 2>/dev/null || echo "0")

    if [ "$ORG_COUNT" -eq 0 ]; then
      log "    No CF orgs found"
      ENTRY=$(jq -n \
        --arg id "$SA_ID" \
        --arg name "$SA_NAME" \
        --arg region "$region" \
        '{subaccount_id: $id, subaccount_name: $name, region: $region, orgs: [], status: "no_cf_orgs"}')
      REPORT_ITEMS=$(echo "$REPORT_ITEMS" | jq --argjson entry "$ENTRY" '. += [$entry]')
      continue
    fi

    ORG_ENTRIES="[]"
    for j in $(seq 0 $((ORG_COUNT - 1))); do
      ORG_GUID=$(echo "$ORGS_JSON" | jq -r ".resources[$j].guid")
      ORG_NAME=$(echo "$ORGS_JSON" | jq -r ".resources[$j].name")

      log "    Collecting quota for org: $ORG_NAME"
      ORG_QUOTA=$(collect_org_quota "$ORG_GUID" "$ORG_NAME")

      if [ -n "$ORG_QUOTA" ] && [ "$ORG_QUOTA" != "{}" ]; then
        ORG_ENTRIES=$(echo "$ORG_ENTRIES" | jq --argjson oq "$ORG_QUOTA" '. += [$oq]')
      fi
    done

    ENTRY=$(jq -n \
      --arg id "$SA_ID" \
      --arg name "$SA_NAME" \
      --arg region "$region" \
      --argjson orgs "$ORG_ENTRIES" \
      '{subaccount_id: $id, subaccount_name: $name, region: $region, orgs: $orgs, status: "ok"}')
    REPORT_ITEMS=$(echo "$REPORT_ITEMS" | jq --argjson entry "$ENTRY" '. += [$entry]')
  done
done

# Build final report
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
REPORT=$(jq -n \
  --arg ts "$TIMESTAMP" \
  --argjson count "$SUBACCOUNT_COUNT" \
  --argjson items "$REPORT_ITEMS" \
  '{
    report_type: "cf_quota_summary",
    generated_at: $ts,
    total_subaccounts: $count,
    subaccounts: $items
  }')

echo "$REPORT"
log "Quota collection complete for ${SUBACCOUNT_COUNT} subaccounts"
